### ISSUE TITLE
Phenotypes not registering in consolidation file

### ISSUE THREAD

**Issue by EKopin** [akoyabio/phenoptrReports#17]
Hi,

I am working with a large number of files although trying to make this work with a single slide image/data. Merging the single file gives all the correct phenotypes, which were re-labeled by the coworker that did the image processing to be tumor, macrophage, etc and not CK+ and CD68+.

Consolidation strips away all the phenotypes and only allows for CD146 and CDCP1. It looks like I can work around it by adding into the consolidation file the other markers, but with> 100 files it would be very obnoxious. Thank you for your help! I am attaching what I hope is relevant.

![analysis](https://user-images.githubusercontent.com/52719831/60920457-762b9b80-a255-11e9-8b08-56c941915790.png)
[Consolidated_data.txt](https://github.com/akoyabio/phenoptrReports/files/3374737/Consolidated_data.txt)
[050118 P29 #02 S10-5399 D8 6_[47440,20189]_cell_seg_data.txt](https://github.com/akoyabio/phenoptrReports/files/3374738/050118.P29.02.S10-5399.D8.6_.47440.20189._cell_seg_data.txt)
[Merge_cell_seg_data.txt](https://github.com/akoyabio/phenoptrReports/files/3374739/Merge_cell_seg_data.txt)

**Comment by AB-Kent** [comment]
phenoptrReports is picky about phenotype names. It requires that positive phenotypes have names ending in '+'. So in this case, CK+ (or tumor+) and CD68+ (or macrophage+) would work but tumor and macrophage do not.

**Comment by EKopin** [comment]
Well although that's obnoxious at least I can change everything in notepad so that it works. More importantly but unrelated, will there be any functionality added in the future of combining multiple phenotypes together with a spatial distribution? As in cell X has to be within 30 microns of cell Y in order for cell Z to be counted within 30 microns of X.

Thank you for your speedy reply.

**Comment by AB-Kent** [comment]
I haven't heard that request before (for conditional count-within, if I understand correctly). Please open a new issue if you would like to discuss it.
