### ISSUE TITLE
Support distance measures in analysis addin

### ISSUE THREAD

**Issue by AB-Kent** [akoyabio/phenoptrReports#18]
Will there be any functionality added in the future of combining multiple phenotypes together with a spatial distribution? As in cell X has to be within 30 microns of cell Y in order for cell Z to be counted within 30 microns of X.

_Originally posted by @EKopin in https://github.com/akoyabio/phenoptrReports/issues/17#issuecomment-509812448_

**Comment by AB-Kent** [comment]
With the above commit, the analysis addin writes the nearest neighbor file in a format which can be read by the addin for a subsequent analysis. In the second analysis, the distance columns can be included in the phenotype definitions using the formula syntax for expressions.

For example, suppose a sample contains CK+, CD8+ and CD68+ cells and the desire is to count, for each CK+ cell,  the number of nearby CD8+ cells which themselves are within 30 microns of a CD68+ cell. To do this,
- First, run the analysis addin on the `Consolidated_data.txt` file. 
  - Specify the phenotypes `CK+`, `CD8+` and `CD68+`. 
  - Select both "Include nearest neighbor summary" and "Save nearest neighbor details"
  - Run the analysis
- Next, run the analysis addin again, selecting for input the `nearest_neighbors.txt` file created in the previous step.
  - Specify the phenotypes `CK+` and ``CD8+/~`Distance to CD68+`<30``. (Note the backticks `` ` `` around the column name.) The second definition will select only CD8+ cells with a nearest CD68+ cell within 30 microns.
  - Select "Include 'count within radius' summary" and "Save nearest neighbor details".
  - Specify the desired radii and run the analysis.

**Comment by EKopin** [comment]
That is brilliant and exactly what I was hoping for, thank you!

**Comment by AB-Kent** [comment]
Note that at present this is only in the development version of phenoptrReports (which also requires the dev version of phenoptr). To try it:
```
devtools::install_github('akoyabio/phenoptr@9000')
devtools::install_github('akoyabio/phenoptrReports@9000')
```
