### ISSUE TITLE
package load error + charachter in column

### ISSUE THREAD

**Issue by michaelmooreny** [akoyabio/phenoptrReports#24]
I received the following error when running analyze consolidated data in phenoptrReports:

Warning: Error in : package or namespace dailed for 'openxslx' in loadNameSpace(j <- i[[1"]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
there is no package called 'zip'

I think the cause of this error may be rooted in my trying to install the dev version of phenoptrReports outlined in your response here:
https://github.com/akoyabio/phenoptrReports/issues/15

I was looking at your response in this thread because I was running into the same problem as the author of that thread, but I may make a separate post about that in the future. 

Thanks, and let me know if there is any other information I can give you!

**Comment by AB-Kent** [comment]
There is no need to install the development version to get that fix, it is in the current release version which you can install with
`devtools::install_github('akoyabio/phenoptrReports')`

The `zip` package should have been installed with `openxlsx` but you can just install it yourself from the RStudio Packages tab. (Click Install, enter the package name "zip".)
