### ISSUE TITLE
Columns have characters values error

### ISSUE THREAD

**Issue by michaelmooreny** [akoyabio/phenoptrReports#25]
After running phenoptrReports on a project I recently received the following error:

Warning: Error in .f: Error reading cell seg data: Expression columns have character values

I think this error is similar to https://github.com/akoyabio/phenoptrReports/issues/15 but I am having some difficulty implementing the solution you outline in the post. Should I go through each of my cell_seg_data files for each image in my project and for example change every instance of CD3 to CD3+/~!is.na(`Cytoplasm CD8 (Opal 690) Mean`) & `Cytoplasm CD8 (Opal 690) Mean`>0.65 ? Or do I just make these changes in the first lines of columns? Do I also need to make this change for all of the phenotypes in my project?

Please let me know if there is any more information I can give you to help solve this problem. Thanks for your help!

**Comment by AB-Kent** [comment]
Which function of phenoptrReports gives you this error? What version of the `readr` package do you have installed? Does updating `readr` fix the problem?

**Comment by michaelmooreny** [comment]
I was running "analyze consolidated data", how do I update the readr package?

**Comment by AB-Kent** [comment]
To update `readr`:
- In RStudio go to the Packages tab
- Scroll down to `readr` and you will see the version you have installed. (The current version is 1.3.1.)
- Click 'Update' and you will see a list of packages with updates available. 
- You may want to "Select all", or just select `readr`, and click Update.

My recollection is that at some point `readr` changed the default column type to double rather than character, that is why I ask that you update.

**Comment by michaelmooreny** [comment]
I just checked and I do have the most updated version of readr (1.3.1) installed. Do you think that changing the headers as in #15 is the correct approach?

**Comment by AB-Kent** [comment]
Can you possibly send me the Consolidated_data.txt file you are using and the Script.R file created by the analysis app? (See my profile for email.)

**Comment by michaelmooreny** [comment]
Sure thing! I'll send those over right now, let me know if there is any other information I can provide you to help solve this problem.

**Comment by AB-Kent** [comment]
This failure was caused by a duplicate header row in the cell seg summary file which makes `readr::read_tsv` interpret every column as text.
