### ISSUE TITLE
Spatial map viewer doesn't recognize component images

### ISSUE THREAD

**Issue by HAL4500** [akoyabio/phenoptrReports#26]
Hi,
I'm encountering an error  when trying to use the spatial map viewer addin. After uploading the consolidated data file and selecting the directory with component and composite images exported from inForm 2.4.4 I get the following error:

`No component image available for Macro_3178_IF_09_11_19_[8855,47803].im3, skipping
Warning in phenoptrReports::nearest_neighbor_map(csd, field, .export_path,`

The viewer itself launches in the browser albeit the images do not load. What could be the problem?

**Comment by AB-Kent** [comment]
The viewer is looking for a file named `Macro_3178_IF_09_11_19_[8855,47803]_component_data.tif` in the directory you selected; is that file present?

**Comment by HAL4500** [comment]
Yes, all of the files are present in the folder.

**Comment by AB-Kent** [comment]
Can you run this small program and reply with the result? (Copy/paste to the RStudio console and press Return; choose your export directory; copy the results and paste to a reply here.) Thanks!

```
base_path = choose.dir() # Choose the same directory you chose in the spatial map viewer
component_path = file.path(base_path, 'Macro_3178_IF_09_11_19_[8855,47803]_component_data.tif')
print(file.exists(component_path))
print(phenoptr::get_field_info(component_path))
```

**Comment by HAL4500** [comment]
I'm dumb, the images were in the folder, but each in a separate one... I grouped them all together and it's working. Thanks for the effort though!

**Comment by AB-Kent** [comment]
😃
