### ISSUE TITLE
File Akoya.png not found in resource path

### ISSUE THREAD

**Issue by drstitch** [akoyabio/phenoptrReports#28]
Hi,

I'm trying to test my data set.
But, some error occurs when "consolidate and summarize" in R addin.  

Reading "1_BR 1801_Scan3_[14061,47724]_cell_seg_data". 
Data is already in microns, no conversion performed
Writing report for "1_BR 1801_Scan3_[14061,47724]_cell_seg_data". 
File Akoya.png not found in resource path
Unable to write summary report
 pandoc document conversion failed with error 99 
Writing consolidated data. 
Writing report for consolidated data. 
File Akoya.png not found in resource path
Unable to write summary report
 pandoc document conversion failed with error 99 
Done! 

Could you tell me how to fix it?
thanks!

**Comment by AB-Kent** [comment]
The recent update of the rmarkdown package to version 1.16 introduced a bug which impacts phenoptrReports. The symptom is that report generation fails with the error
File Akoya.png not found in resource path 
If you get this error, the simplest fix is to update to the development version of rmarkdown, which has been fixed. Update with the R command
remotes::install_github("rstudio/rmarkdown")

If you have not updated rmarkdown, I recommend waiting for version 1.17.

The rmarkdown issue is here:
https://github.com/rstudio/rmarkdown/issues/1667

**Comment by drstitch** [comment]
fantastic. Thanks!

**Comment by AB-Kent** [comment]
Note: the `rmarkdown` package is now at version 2.0. This bug has been fixed and there is no longer any need to install from github.
