### ISSUE TITLE
Touching cells does not display correct segmentation maps. 

### ISSUE THREAD

**Issue by gcakoyabio** [akoyabio/phenoptrReports#37]
![Capture](https://user-images.githubusercontent.com/46654780/83073419-0a514d80-a036-11ea-8ad8-b38f9a7368db.PNG)

**Comment by AB-Kent** [comment]
Can you send me data to reproduce this? I would need the composite, component and segmentation maps for that field and associated cell seg data. See my profile for email address.

**Comment by AB-Kent** [comment]
This was caused by using a Consolidated_data file that did not correspond to the associated image.
