### ISSUE TITLE
R session is aborted when spatial map viewer cannot find requested phenotype in image

### ISSUE THREAD

**Issue by gcakoyabio** [akoyabio/phenoptrReports#38]
Reproduce error by calling a phenotype combination that does not exist in the image as phenotype 1, e.g., CD8+/PD-1+ and specify phenotype 2, e.g., CK+.

**Comment by AB-Kent** [comment]
Is there any error message or stack trace in the R console when you do this? What version of phenoptrReports are you using?

**Comment by gcakoyabio** [comment]
Kent I updated PhenoptrReports and no longer see this error using R version 4.0

**Comment by gcakoyabio** [comment]
I updated PhenoptrReports. Updating the software seems to have fixed the error.
