### ISSUE TITLE
Consolidate and summarize 

### ISSUE THREAD

**Issue by tanerhf** [akoyabio/phenoptrReports#40]
Hello, 

I am trying to consolidate my merge files, and am having some issues. When I input all of them together I get a warning: 

Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "", and the latter is "Cell seg data summary". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
Joining, by = "Slide ID"
Joining, by = "Slide ID"
Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "", and the latter is "Cell seg data summary". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
Warning: Error in split_phenotypes: No positive phenotypes found.

The files are not consolidated. I ran the files one at a time to see what happens. I am able to get separate files this way and all my populations of interested have the (+). 

Any help would be greatly appreciated!

Hulya

**Comment by SDJ7007** [comment]
Hey 
Did you get any answer for this? I am receiving the same error. 
Thank you.
-Shweta Johari

**Comment by AB-Kent** [comment]
The warnings about the vignette title were fixed long ago; please update to the latest phenoptr and phenoptrReports. The consolidation app does require that positive phenotypes are represented in the data being consolidated.
