### ISSUE TITLE
cannot install rtree package in R 4.0

### ISSUE THREAD

**Issue by Athanasios72** [akoyabio/phenoptrReports#41]
Hi  Kent,
I am not able to install the rtree package on RStudio (R version 4.0, cluster environment) using: **devtools::install_github("akoyabio/rtree")**
Is there a way to solve this as it is required by the "phenoptrReports" package to do spatial analysis of inForm consolidated data?
Thank you.
Kind regards,
Athanasios

**Comment by AB-Kent** [comment]
Hi, What OS are you on? What error message did you get?

**Comment by Athanasios72** [comment]
I am using Windows 10 and accessing the local RStudio cluster via the Mozilla Firefox browser.

The error output I get is massive with the last part being:
**_make: *** [rtree.o] Error 1
ERROR: compilation failed for package ‘rtree’
* removing ‘/home/akoulis/.rstudio/library/rtree’
Error: Failed to install 'rtree' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp6I3mXo/file4d47e6632eb2b/rtree_0.1.0.tar.gz’ had non-zero exit status_**

Thank you.

**Comment by AB-Kent** [comment]
So you are installing rtree on the cluster? What OS is the cluster running?

In the massive error output there should be a more descriptive error, can you find it?

Kent
________________________________

**Comment by AB-Kent** [comment]
There seems to be an incompatibility between the latest version (1.75.0-0) of the R package BH and the Akoya rtree package. This manifests as a huge number of compilation errors when trying to install rtree, ending in failure. 

For now, a fix is to install the previous version of BH before installing rtree, using the R commands
remotes::install_version('BH', '1.72.0-3')
remotes::install_github('akoyabio/rtree')

Important: When you install rtree with the second command above, it will ask you if you want to update BH. Do not update BH!!

**Comment by Athanasios72** [comment]
Thank you Kent.
Unfortunately this did not solve the issue. The cluster I am using is running on x86_64-pc-linux-gnu (64-bit).

After successfully installing the previous version of BH, I get the following error output:
> remotes::install_github('akoyabio/rtree')
Downloading GitHub repo akoyabio/rtree@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                               
2: CRAN packages only                
3: None                              
4: BH   (1.72.0-3 -> 1.75.0-0) [CRAN]
5: Rcpp (1.0.5    -> 1.0.6   ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
✓  checking for file ‘/tmp/RtmpUjNjiz/remotes14664aa21222a/akoyabio-rtree-37cb2a2/DESCRIPTION’ ...
─  preparing ‘rtree’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rtree_0.1.0.tar.gz’
   
Installing package into ‘/home/akoulis/.rstudio/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘rtree’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/config/binaries/R/4.0.2/lib64/R/include" -DNDEBUG  -I'/config/binaries/R/4.0.2/R_libraries/Rcpp/include' -I'/home/akoulis/.rstudio/library/BH/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/config/binaries/R/4.0.2/lib64/R/include" -DNDEBUG  -I'/config/binaries/R/4.0.2/R_libraries/Rcpp/include' -I'/home/akoulis/.rstudio/library/BH/include' -I/usr/local/include   -fpic  -g -O2  -c rtree.cpp -o rtree.o
In file included from /home/akoulis/.rstudio/library/BH/include/boost/bind/mem_fn.hpp:25,
                 from /home/akoulis/.rstudio/library/BH/include/boost/mem_fn.hpp:22,
                 from /home/akoulis/.rstudio/library/BH/include/boost/function/detail/prologue.hpp:18,
                 from /home/akoulis/.rstudio/library/BH/include/boost/function.hpp:30,
                 from /home/akoulis/.rstudio/library/BH/include/boost/algorithm/string/detail/find_iterator.hpp:18,
                 from /home/akoulis/.rstudio/library/BH/include/boost/algorithm/string/find_iterator.hpp:24,
                 from /home/akoulis/.rstudio/library/BH/include/boost/algorithm/string/iter_find.hpp:27,
                 from /home/akoulis/.rstudio/library/BH/include/boost/algorithm/string/split.hpp:16,
                 from /home/akoulis/.rstudio/library/BH/include/boost/algorithm/string.hpp:23,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/io/wkt/read.hpp:29,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/io/wkt/wkt.hpp:17,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/strategies/cartesian/buffer_end_round.hpp:27,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/strategies/strategies.hpp:49,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/geometry.hpp:49,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry.hpp:17,
                 from rtree.cpp:10:
/home/akoulis/.rstudio/library/BH/include/boost/get_pointer.hpp:48:40: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                        ^~~~~~~~
In file included from /config/binaries/gcc/8.3.0/include/c++/8.3.0/bits/locale_conv.h:41,
                 from /config/binaries/gcc/8.3.0/include/c++/8.3.0/locale:43,
                 from /config/binaries/gcc/8.3.0/include/c++/8.3.0/iomanip:43,
                 from /config/binaries/R/4.0.2/R_libraries/Rcpp/include/RcppCommon.h:52,
                 from /config/binaries/R/4.0.2/R_libraries/Rcpp/include/Rcpp.h:27,
                 from rtree.cpp:9:
/config/binaries/gcc/8.3.0/include/c++/8.3.0/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /home/akoulis/.rstudio/library/BH/include/boost/scoped_ptr.hpp:13,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/index/detail/rtree/query_iterators.hpp:14,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/index/rtree.hpp:86,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/detail/within/multi_point.hpp:33,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/detail/within/implementation.hpp:44,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/detail/covered_by/implementation.hpp:25,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/covered_by.hpp:24,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/detail/distance/multipoint_to_geometry.hpp:22,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/detail/distance/implementation.hpp:26,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/detail/comparable_distance/implementation.hpp:22,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/comparable_distance.hpp:23,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:28,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:35,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/algorithms/buffer.hpp:41,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry/geometry.hpp:54,
                 from /home/akoulis/.rstudio/library/BH/include/boost/geometry.hpp:17,
                 from rtree.cpp:10:
/home/akoulis/.rstudio/library/BH/include/boost/smart_ptr/scoped_ptr.hpp:74:31: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit scoped_ptr( std::auto_ptr<T> p ) BOOST_SP_NOEXCEPT : px( p.release() )
                               ^~~~~~~~
In file included from /config/binaries/gcc/8.3.0/include/c++/8.3.0/bits/locale_conv.h:41,
                 from /config/binaries/gcc/8.3.0/include/c++/8.3.0/locale:43,
                 from /config/binaries/gcc/8.3.0/include/c++/8.3.0/iomanip:43,
                 from /config/binaries/R/4.0.2/R_libraries/Rcpp/include/RcppCommon.h:52,
                 from /config/binaries/R/4.0.2/R_libraries/Rcpp/include/Rcpp.h:27,
                 from rtree.cpp:9:
/config/binaries/gcc/8.3.0/include/c++/8.3.0/bits/unique_ptr.h:53:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
g++ -std=gnu++11 -shared -L/config/binaries/R/4.0.2/lib64/R/lib -L/usr/local/lib64 -o rtree.so RcppExports.o rtree.o -L/config/binaries/R/4.0.2/lib64/R/lib -lR
installing to /home/akoulis/.rstudio/library/00LOCK-rtree/00new/rtree/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
sh: line 1: 1337780 Segmentation fault      R_TESTS= '/config/binaries/R/4.0.2/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpmCJP6h/file14694d1dbacc2'

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE, where = env)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 6: Rcpp::loadModule(module = "rtreecpp", what = TRUE, env = ns,     loadNow = TRUE)
 7: (function (ns) Rcpp::loadModule(module = "rtreecpp", what = TRUE, env = ns,     loadNow = TRUE))(<environment>)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch((function (ns) Rcpp::loadModule(module = "rtreecpp", what = TRUE, env = ns,     loadNow = TRUE))(<environment>), error = function(e) e)
12: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
13: eval(substitute(tryCatch(FUN(WHERE), error = function(e) e),     list(FUN = f, WHERE = where)), where)
14: .doLoadActions(where, attach)
15: methods::cacheMetaData(ns, TRUE, ns)
16: loadNamespace(package, lib.loc)
17: doTryCatch(return(expr), name, parentenv, handler)
18: tryCatchOne(expr, names, parentenv, handlers[[1L]])
19: tryCatchList(expr, classes, parentenv, handlers)
20: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
21: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
22: withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
23: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
24: doTryCatch(return(expr), name, parentenv, handler)
25: tryCatchOne(expr, names, parentenv, handlers[[1L]])
26: tryCatchList(expr, classes, parentenv, handlers)
27: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
28: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
29: tools:::.test_load_package("rtree", "/home/akoulis/.rstudio/library/00LOCK-rtree/00new")
An irrecoverable exception occurred. R is aborting now ...
ERROR: loading failed
* removing ‘/home/akoulis/.rstudio/library/rtree’
Error: Failed to install 'rtree' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpUjNjiz/file14664a3447eac5/rtree_0.1.0.tar.gz’ had non-zero exit status

**Comment by AB-Kent** [comment]
Hi,

Unfortunately my ability to support rtree on linux is very limited. Here are a couple of things you can try.

First, update to the latest Rcpp (1.0.6). Then, either
- Repeat the installation with BH 1.72 using the previous instructions

or 
- Install the (new) branch of rtree that uses BH 1.75 with the command
remotes::install_github('akoyabio/rtree@BH_1.75')

If neither of those works, post the output from the second option and I will try to get some support from the Rcpp folks.

**Comment by Athanasios72** [comment]
Thank you Kent.

I updated to the latest Rcpp (1.0.6) and then run:

remotes::install_version('BH', '1.72.0-3')
remotes::install_github('akoyabio/rtree')

This time rtree installed successfully.

Cheers.

**Comment by AB-Kent** [comment]
Yay! Thanks for letting me know.
