### ISSUE TITLE
Using Phenoptr reports with non-Vectra TIFFs

### ISSUE THREAD

**Issue by man154** [akoyabio/phenoptrReports#42]
I have a multi-layered TIFF which I generated from a multi-channel fluorescence image. I also have the corresponding RGB/flattened/composite image. I wish to make a spatial distance map with phenoptrReports. The Spatial Map Viewer can locate the file, but throws this error. Any suggestion? 

Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning: Removed 1 rows containing missing values (geom_segment).
Warning: Removed 1 rows containing missing values (geom_text).
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning: Removed 1 rows containing missing values (geom_segment).
Warning: Removed 1 rows containing missing values (geom_text).
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning: Error in grid.Call.graphics: non-finite location and/or size for viewport
  178: recordGraphics
  177: grid.draw.gTree
  175: print.ggplot
  167: func
  165: f
  164: Reduce
  155: do
  154: hybrid_chain
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: renderFunc
   82: output$plot
    2: shiny::runApp
    1: phenoptrReports::spatial_map_viewer

**Comment by AB-Kent** [comment]
The spatial map viewer relies on spatial reference information in the component data files written by inForm. Your TIFF file probably does not include this.
