### ISSUE TITLE
Identifying background/noise from signal

### ISSUE THREAD

**Issue by Jeff87075** [akoyabio/phenoptrReports#43]
I understand that the inForm software machine learning algorithm already performs the phenotyping function. However, instead of analyzing the discrete output (e.g. number of PD-1+CD8+ cells vs number of PD-1+CD4+ cells) I was wondering is it possible to work directly with the Opal fluor intensities to obtain a set of continuous data (e.g. PD-1 **intensity** in CD8+ versus CD4+ cells). 

So I want to ask is there any way or method to obtain the threshold level that is considered background/noise such that I can filter away intensities lower than the cutoff and then apply a continuous scale to the remaining intensities? Or would it work if I looked at all the positive cells identified by inForm phenotyping and take the minimum Opal fluor intensity measured in these cells? Many thanks.

**Comment by AB-Kent** [comment]
inForm doesn't compute threshold levels. It does output fluor intensities in the cell seg data file so the data is available. The phenoptrReports "Analyze consolidated data" addin can compute mean expression of PD-1 per phenotype but if you want anything more detailed you will have to do it yourself. Filtering the data for the phenotypes of interest and looking at the associated expression levels sounds like a good start.

You can also use the scoring function in inForm to manually explore expression levels and choose a background level that makes sense to you.

**Comment by Jeff87075** [comment]
Thanks for the prompt response! As developers of the software, would you have any recommendations as to what methods or approaches are preferable in finding the background level of expression?

**Comment by AB-Kent** [comment]
That is a discussion you should have with your FAS, this is not a forum for general application support.
