### ISSUE TITLE
Data Consolidation creates duplicate columns instead of merging

### ISSUE THREAD

**Issue by cduerrschmid** [akoyabio/phenoptrReports#45]
I am consolidating merged cell seg data from 3 binary phenotyping projects. the output consolidated_data.txt has a ".x" or ".y" added to the end of each column. There are "duplicate" columns, like Sample Name.x/Sample Name.y etc.
This project worked just fine with a prior version of PR (of course I don't know which one, since that information is gone after updating everything).
The consolidated_data.html still seems fine, however the txt can't be used for spatial analysis.
[Consolidated_data.txt](https://github.com/akoyabio/phenoptrReports/files/6631842/Consolidated_data.txt)
[Consolidated_data.zip](https://github.com/akoyabio/phenoptrReports/files/6631847/Consolidated_data.zip)
[merge cell seg data.zip](https://github.com/akoyabio/phenoptrReports/files/6631868/merge.cell.seg.data.zip)

Console output is pretty much useless, as there is no error returned
:
"R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> phenoptrReports:::addin_10_merge()
Loading required package: shiny

Listening on http://127.0.0.1:4412
> phenoptrReports:::addin_10_merge()

Listening on http://127.0.0.1:4412
> phenoptrReports:::addin_10_merge()

Listening on http://127.0.0.1:4412
> phenoptrReports:::addin_20_consolidate()

Listening on http://127.0.0.1:4412
Reading "CD3_Merge_cell_seg_data". 
Data is already in microns, no conversion performed                                                                                                                                                   
Writing report for "CD3_Merge_cell_seg_data". 
Loading required package: UpSetR
Reading "FoxP3_Merge_cell_seg_data". 
Data is already in microns, no conversion performed                                                                                                                                                   
Writing report for "FoxP3_Merge_cell_seg_data". 
Reading "Ki67_Merge_cell_seg_data". 
Data is already in microns, no conversion performed                                                                                                                                                   
Writing report for "Ki67_Merge_cell_seg_data". 
Writing consolidated data. 
Writing report for consolidated data.                                                                                                                            
Done! 

> "

**Comment by AB-Kent** [comment]
Fixed now, thanks for the report!
