### ISSUE TITLE
Charts word doc is empty and spatial viewer does not load

### ISSUE THREAD

**Issue by cduerrschmid** [akoyabio/phenoptrReports#46]
another bug report: consolidation works perfectly fine now, but when analyzing consolidated data, the word docs with the charts does not contain charts, and the spatial viewer does not load. the results excel file still contains all results.

I can confirm this worked in the past. I was able to reproduce the error on a customer computer and my personal computer, and my colleague Avik also encounters the same error. we're all on the latest version of R, R Studio and R tools, and P/PR.

[Script.zip](https://github.com/akoyabio/phenoptrReports/files/6634276/Script.zip)

[session_info.txt](https://github.com/akoyabio/phenoptrReports/files/6634273/session_info.txt)

[Results.xlsx](https://github.com/akoyabio/phenoptrReports/files/6634270/Results.xlsx)

[Charts.docx](https://github.com/akoyabio/phenoptrReports/files/6634269/Charts.docx)

**Comment by AB-Kent** [comment]
The charts are failing because the Slide ID is empty in Results.xlsx. How did that happen? The empty cells read as NA so they are omitted from the charts. Can you fill in a Slide ID and re-run the charts?

Please open a separate issue for the spatial viewer and give more details. What does "does not load" look like? Are there any errors or messages in the console?

**Comment by cduerrschmid** [comment]
Replying in reverse order:

- the slide ID was removed bc the analyze consolidated data autofilled the entire slide ID in the analysis window, where you can pick the prefix to be removed. changing this allowed me to run the spatial viewer (when I wrote it does not load, i meant it doesn't even open a browser window this is fixed now by keeping the slide ID intact). 
 
- The charts still don't show up, even with the slide ID left intact, the charts word document only has text headers, no charts.

[console.txt](https://github.com/akoyabio/phenoptrReports/files/6648714/console.txt)
[analyzed.zip](https://github.com/akoyabio/phenoptrReports/files/6648716/analyzed.zip)

**Comment by AB-Kent** [comment]
Fixed the charts and no longer offer to remove the entire Slide ID, both in a new 0.2.13 release.

Thanks for the bug reports and sorry about the churn...
