### ISSUE TITLE
Spatial Map Viewer Error

### ISSUE THREAD

**Issue by cduerrschmid** [akoyabio/phenoptrReports#51]
> phenoptrReports:::addin_35_spatial_map_viewer()

Listening on http://127.0.0.1:6228
> phenoptrReports::spatial_map_viewer('D:/Users/cduerrschmid/OneDrive - Akoya Biosciences/PhenoptrReports Application Note/InForm Export/consolidated/Consolidated_data.txt', 'D:/Users/cduerrschmid/OneDrive - Akoya Biosciences/PhenoptrReports Application Note/InForm Export')
Starting app
Error: 'read_composite_info' is not an exported object from 'namespace:phenoptr'                                                                                                                      
>

**Comment by AB-Kent** [comment]
Sorry about that! `read_composite_info` was not in the master branch of phenoptr; now it is. Please reinstall both phenoptr and phenoptrReports with the commands

    remotes::install_github('akoyabio/phenoptr')
    remotes::install_github('akoyabio/phenoptrReports')
