### ISSUE TITLE
PhenoprReports update-spatial map viewer not working

### ISSUE THREAD

**Issue by aakoya** [akoyabio/phenoptrReports#52]
I updated phenoptrReports yesterday, and I'm no longer able to use the spatial map viewer with a data set that worked previously. I've attached the error I received when trying to run this addin
![spatial viewer error](https://user-images.githubusercontent.com/91702422/135535635-f9cb31f0-6f42-497a-8c6e-d432cc939288.png)
.

**Comment by AB-Kent** [comment]
This was fixed by upgrading inForm to version 2.6

**Comment by aehaggerty** [comment]
Can I install a previous version of PR? I have customers that cannot update to the latest inform yet but would still like to utilize the phenoptrReports spatial map viewer. Any advice on how to do this is much appreciated. Thanks!

**Comment by AB-Kent** [comment]
Please try the development version of phenoptr and phenoptrReports, I think this is fixed now. Let me know if it works!

Install with
```
remotes::install_github('akoyabio/phenoptr@9000')
remotes::install_github('akoyabio/phenoptrReports@9000')
```

**Comment by aehaggerty** [comment]
Hi Kent,
That works perfectly! Thank you so much!

Best,
Agnes

Agnes Haggerty, PhD  |  Biomarker Specialist (Americas)
Email:  ***@***.******@***.***>
Cell:  650.384.5761
Akoya Biosciences
www.akoyabio.com<http://www.akoyabio.com/>

**Comment by AB-Kent** [comment]
Note: With older inForm images that do not have any metadata, the error message is
`Error: Result 1 must be a single string, not NULL of length 0`
