### ISSUE TITLE
Consolidated and Summary Report- Warning 

### ISSUE THREAD

**Issue by SDJ7007** [akoyabio/phenoptrReports#53]
Hello, I am using phenoptr for my analysis and receiving this warning while the consolidation is occuring: 
 
Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "", and the latter is "Cell seg data summary". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
Joining, by = "Slide ID"
Joining, by = "Slide ID"
Quitting from lines 168-190 (Cell_seg_summary_report.Rmd)

Please do help me. 
Thank you.
Regards,
Shweta Johari

**Comment by AB-Kent** [comment]
Please update to the latest phenoptr and phenoptrReports.

**Comment by SDJ7007** [comment]
Thank you. Yes I did this, I got into another error of not having both the HTML files of the projects but just one.

**Comment by SDJ7007** [comment]
When I updated the R to 4.1, it did not read my one project.
