### ISSUE TITLE
One project is gettting consolidated but not the second. 

### ISSUE THREAD

**Issue by SDJ7007** [akoyabio/phenoptrReports#54]
Good evening, 
I have two projects and want to consolidate and summarize both but I am only getting the summary data of one. 

Listening on http://127.0.0.1:4996
Reading "Merge_cell_seg_data". 
Data is already in microns, no conversion performed                                                                                                         
Adding Slide ID column to Merge_cell_seg_data.txt
Writing report for "Merge_cell_seg_data". 
Quitting from lines 174-196 (Cell_seg_summary_report.Rmd) 
Unable to write summary report
 All renaming inputs must be named. 
Writing consolidated data. 
Writing report for consolidated data.                                                                                  
Quitting from lines 174-196 (Cell_seg_summary_report.Rmd) 
Unable to write summary report
 All renaming inputs must be named. 
Done! 

In addition, the consolidated and summarized data of another when I put it in the analyze consolidated adding, it is showing as please input data.

May I please know what I am doing wrong? What can be done?

Thank you
-Shweta Johari

**Comment by SDJ7007** [comment]
Sir,
Thank you for your patience and for closing the issue on that platform. 
Could I please know why am I receiving only one output (no consolidation of both projects but only one HTML summary of one project) and how can I overcome it, please?
Thank you.

Yours sincerely,
Shweta Johari

**Comment by AB-Kent** [comment]
The problem is that you have a space in one of the phenotype names - "F4/80 +". This is interpreted as two phenotypes and causes the problem you see.
