### ISSUE TITLE
Merge seg files bug

### ISSUE THREAD

**Issue by JpGuegan** [akoyabio/phenoptrReports#55]
With the new version of PhenoptrReport (3.1), the merge_cell_seg_file function stops on files with no detected cells (empty cell seg file with just the column names) and we have to stop the command because it lasts forever. However, when we processed the same batch of files with an older version (v2.4), the script runs smoothly and a merge_cell_seg_file is created. How to solve this?

**Comment by AB-Kent** [comment]
That's odd, the merge function has changed very little since version 0.2.4. Can you share a set of files that fail? (Email a link to files.) Also please show the output of the command
devtools::session_info()

**Comment by JpGuegan** [comment]
Here is a link to some files https://explicyte.transfernow.net/dl/20211208q7dRXnGK

and below is the session info

- Session info  ------------------------------------------------------------------------------------------------------------------------------------------------------
 hash: woman cook: medium-dark skin tone, snowboarder, flag: St. Kitts & Nevis

 setting  value
 version  R version 4.1.1 (2021-08-10)
 os       Windows Server x64 (build 17763)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       Europe/Paris
 date     2021-12-08
 rstudio  2021.09.0+351 Ghost Orchid (desktop)
 pandoc   NA

- Packages -----------------------------------------------------------------------------------------------------------------------------------------------------------
 package        * version date (UTC) lib source
 abind            1.4-5   2016-07-21 [1] CRAN (R 4.1.1)
 assertthat       0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
 backports        1.3.0   2021-10-27 [1] CRAN (R 4.1.1)
 broom            0.7.10  2021-10-31 [1] CRAN (R 4.1.1)
 cachem           1.0.6   2021-08-19 [1] CRAN (R 4.1.1)
 callr            3.7.0   2021-04-20 [1] CRAN (R 4.1.1)
 car              3.0-12  2021-11-06 [1] CRAN (R 4.1.1)
 carData          3.0-4   2020-05-22 [1] CRAN (R 4.1.1)
 cli              3.1.0   2021-10-27 [1] CRAN (R 4.1.1)
 colorspace       2.0-2   2021-06-24 [1] CRAN (R 4.1.1)
 crayon           1.4.2   2021-10-29 [1] CRAN (R 4.1.1)
 DBI              1.1.1   2021-01-15 [1] CRAN (R 4.1.1)
 desc             1.4.0   2021-09-28 [1] CRAN (R 4.1.1)
 devtools         2.4.2   2021-06-07 [1] CRAN (R 4.1.1)
 digest           0.6.28  2021-09-23 [1] CRAN (R 4.1.1)
 dplyr            1.0.7   2021-06-18 [1] CRAN (R 4.1.1)
 DT               0.19    2021-09-02 [1] CRAN (R 4.1.1)
 ellipsis         0.3.2   2021-04-29 [1] CRAN (R 4.1.1)
 ExplicyteTools   0.1.0   2021-12-02 [1] local
 fansi            0.5.0   2021-05-25 [1] CRAN (R 4.1.1)
 fastmap          1.1.0   2021-01-25 [1] CRAN (R 4.1.1)
 fs               1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
 generics         0.1.1   2021-10-25 [1] CRAN (R 4.1.1)
 ggplot2          3.3.5   2021-06-25 [1] CRAN (R 4.1.1)
 ggpubr           0.4.0   2020-06-27 [1] CRAN (R 4.1.1)
 ggsignif         0.6.3   2021-09-09 [1] CRAN (R 4.1.1)
 glue             1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
 gtable           0.3.0   2019-03-25 [1] CRAN (R 4.1.0)
 htmltools        0.5.2   2021-08-25 [1] CRAN (R 4.1.1)
 htmlwidgets      1.5.4   2021-09-08 [1] CRAN (R 4.1.1)
 janitor          2.1.0   2021-01-05 [1] CRAN (R 4.1.1)
 knitr            1.36    2021-09-29 [1] CRAN (R 4.1.1)
 lifecycle        1.0.1   2021-09-24 [1] CRAN (R 4.1.1)
 lubridate        1.8.0   2021-10-07 [1] CRAN (R 4.1.1)
 magrittr         2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 memoise          2.0.0   2021-01-26 [1] CRAN (R 4.1.1)
 munsell          0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
 pillar           1.6.4   2021-10-18 [1] CRAN (R 4.1.1)
 pkgbuild         1.2.0   2020-12-15 [1] CRAN (R 4.1.0)
 pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 pkgload          1.2.3   2021-10-13 [1] CRAN (R 4.1.1)
 plyr             1.8.6   2020-03-03 [1] CRAN (R 4.1.0)
 prettyunits      1.1.1   2020-01-24 [1] CRAN (R 4.1.0)
 processx         3.5.2   2021-04-30 [1] CRAN (R 4.1.1)
 ps               1.6.0   2021-02-28 [1] CRAN (R 4.1.1)
 purrr            0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6               2.5.1   2021-08-19 [1] CRAN (R 4.1.1)
 Rcpp             1.0.7   2021-07-07 [1] CRAN (R 4.1.1)
 remotes          2.4.1   2021-09-29 [1] CRAN (R 4.1.1)
 reshape2         1.4.4   2020-04-09 [1] CRAN (R 4.1.0)
 rlang            0.4.12  2021-10-18 [1] CRAN (R 4.1.1)
 rprojroot        2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 rstatix          0.7.0   2021-02-13 [1] CRAN (R 4.1.1)
 scales           1.1.1   2020-05-11 [1] CRAN (R 4.1.0)
 sessioninfo      1.2.1   2021-11-02 [1] CRAN (R 4.1.1)
 snakecase        0.11.0  2019-05-25 [1] CRAN (R 4.1.1)
 stringi          1.7.5   2021-10-04 [1] CRAN (R 4.1.1)
 stringr          1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
 testthat         3.1.0   2021-10-04 [1] CRAN (R 4.1.1)
 tibble           3.1.5   2021-09-30 [1] CRAN (R 4.1.1)
 tidyr            1.1.4   2021-09-27 [1] CRAN (R 4.1.1)
 tidyselect       1.1.1   2021-04-30 [1] CRAN (R 4.1.1)
 usethis          2.1.3   2021-10-27 [1] CRAN (R 4.1.1)
 utf8             1.2.2   2021-07-24 [1] CRAN (R 4.1.1)
 vctrs            0.3.8   2021-04-29 [1] CRAN (R 4.1.1)
 withr            2.4.2   2021-04-18 [1] CRAN (R 4.1.1)
 xfun             0.27    2021-10-18 [1] CRAN (R 4.1.1)

 [1] C:/Users/JPGUEGAN/Documents/R/win-library/4.1
 [2] C:/Program Files/R/R-4.1.1/library

**Comment by AB-Kent** [comment]
Hmm, I'm able to merge that data without problem. My system is very similar to yours, though Windows 10 vs Windows Server.

Is there anything else you can tell me about the failure? What versions of readr and vroom do you have, they are not in the list above.

**Comment by JpGuegan** [comment]
Ok, that's weird because I have tested it on two different computers (Windows10 & server). Here are the versions of readr (v2.0.2) and vroom (1.5.5).

**Comment by AB-Kent** [comment]
Please update both readr and vroom to the latest versions; you seem to have run into this readr bug: https://github.com/tidyverse/readr/issues/1297

**Comment by JpGuegan** [comment]
Thanks! The updates fixed the problem. Sorry for the inconvenience!
