### ISSUE TITLE
Number of component is not same for Unmixing Quality Report

### ISSUE THREAD

**Issue by SDJ7007** [akoyabio/phenoptrReports#58]
Good afternoon,
In unmixing quality report, I am receiving, "missing components" in the results.
May I please know the meaning of what does missing components mean as well as what can I do to overcome this? 
Thank you. 

Regards,
SDJ

**Comment by rezapour20882** [comment]
That is the warning related to the images are not "all" having the same component.
Please look at the images and make sure they all are having the same components.

**Comment by rezapour20882** [comment]
please le us know if you have any further question!
