### ISSUE TITLE
phenoptrReports package does not install with R version 4.2.0

### ISSUE THREAD

**Issue by shberry1998** [akoyabio/phenoptrReports#59]
the phenoptrReports package is not compatible with and does not install if using R version 4.2.0 (the newest update)

**Comment by rezapour20882** [comment]
Hello,

I am currently using R version of 4.2.0, and able to use PhenoptrReports.
Is there a particular function that you are experiencing the issue?
I would appreciate it if you could provide us with more details!

Best,
Mahdi

**Comment by rezapour20882** [comment]
Hello,

I update my R version to  4.2.0 and installed phenoptrReports  with no issue.
If your issue persists, as you might know, you can have few versions of R at the same time. Just go to tools>Global options>Generals>R version>....restart your R session and you are set.

Best,
Mahdi
